name: Run ascii23 tests and benchmark
run-name: ${{ github.actor }} is running ascii23 tests and benchmark
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-22.04
          - macos-12
          - windows-2022
    runs-on: ${{ matrix.platform }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: install gcc (unix/macos)
        if: "runner.os != 'windows'"
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
      - name: install cppcheck (unix)
        if: "runner.os == 'linux'"
        run: |
          sudo apt-get install cppcheck -y
      - name: install cppcheck (macos)
        if: "runner.os == 'macos'"
        run: |
          brew install cppcheck
      - name: install gcc and cppcheck (windows)
        if: "runner.os == 'windows'"
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install mingw cppcheck -y
        
      - name: make tests
        run: |
          make test_impl
          make test_header
          make test_lib
      - name: make dll test (windows)
        if: "runner.os == 'windows'"
        run: |
          make test_dll
          
      - name: make benchmark
        run: |
          make bench_impl
          
      - name: run implementation test
        run:
          ./bin/test_impl
      - name: run header-only test
        run:
          ./bin/test_header
      - name: run static linking test
        run:
          ./bin/test_lib
      - name: run dll test (windows)
        if: "runner.os == 'windows'"
        run:
          ./bin/test_dll
          
      - name: run benchmark
        run: |
          ./bin/bench_impl
