name: Run ascii23 tests and benchmark
run-name: ${{ github.actor }} is running ascii23 tests and benchmark
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-22.04
          - windows-2022
    runs-on: ${{ matrix.platform }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: install gcc (ubuntu)
        if: "runner.os != 'windows'"
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
      - name: install cppcheck (ubuntu)
        if: "runner.os == 'linux'"
        run: |
          sudo apt-get install cppcheck -y
      
      - name: run cppcheck (ubuntu)
        run: |
          make cppcheck
      
      - name: make tests
        run: |
          make test_impl
          make test_header
          make test_lib
      - name: make dll test (windows)
        if: "runner.os == 'windows'"
        run: |
          make test_dll
          
      - name: make benchmark
        run: |
          make bench_impl
          
      - name: run tests (ubuntu)
        if: "runner.os != 'windows'"
        run: |
          ./bin/test_impl
          ./bin/test_header
          ./bin/test_lib
      - name: run tests (windows)
        if: "runner.os == 'windows'"
        run: |
          "bin/test_impl.exe"
          "bin/test_header.exe"
          "bin/test_lib.exe"
          "bin/test_dll.exe"
          
      - name: run benchmark (ubuntu)
        if: "runner.os != 'windows'"
        run: |
          ./bin/bench_impl
      - name: run benchmark (windows)
        if: "runner.os == 'windows'"
        run: |
          "bin/bench_impl.exe"
