name: Run ascii23 tests and benchmark
run-name: ${{ github.actor }} is running ascii23 tests and benchmark
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: install gcc
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
          
      - name: install cppcheck
        run: |
          sudo apt-get install cppcheck -y
      - name: make cppcheck
        run: |
          make cppcheck
        
      - name: make tests and benchmark
        run: |
          make test_impl
          make test_header
          make test_lib
          make bench_impl
          
      - name: run test_impl
        run:
          ./bin/test_impl
      - name: run test_header
        run:
          ./bin/test_header
      - name: run test_lib
        run:
          ./bin/test_lib
      - name: run bench_impl
        run: |
          ./bin/bench_impl
